version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d1tggiripnbc73ca9fvg-a:5432/cansupport_d
      SPRING_DATASOURCE_USERNAME: chandrakesh_ram
      SPRING_DATASOURCE_PASSWORD: WNgKKXz9OAUssS0rqWQp2ZLjTYLBHslQ
      SPRING_MAIL_HOST: sandbox.smtp.mailtrap.io
      SPRING_MAIL_PORT: 2525
      SPRING_MAIL_USERNAME: 4297b546c8aac6
      SPRING_MAIL_PASSWORD: 889d2c2d862f12

  db:
    image: postgres:16
    container_name: cansupport-db
    restart: always
    environment:
      POSTGRES_DB: cansupport_db
      POSTGRES_USER: chandrakesh_ram
      POSTGRES_PASSWORD: WNgKKXz9OAUssS0rqWQp2ZLjTYLBHslQ
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: